# Generated by Django 5.0.4 on 2024-05-02 01:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('units', models.IntegerField()),
                ('genre', models.CharField(max_length=80)),
                ('type_publication', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('date_release', models.DateTimeField()),
                ('price_cost', models.IntegerField()),
                ('price_sell', models.IntegerField()),
                ('date_register', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='OutputProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_output', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('unist', models.IntegerField()),
                ('description', models.CharField(max_length=120)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.products')),
            ],
        ),
        migrations.CreateModel(
            name='InputProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_purchase', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('units_products', models.IntegerField()),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.products')),
            ],
        ),
    ]
